alter session set container = XEPDB1;

insert into SRM_OWNER.HCO_SETTINGS (HCO_SETTINGS_ID, GOAL_DATE, AUTO_EMAIL_YN, FEEDBACK_EMAIL_CSV, MASK_REQUEST_EMAIL_CSV, ACTIVITY_EMAIL_CSV) values (1, DATE '2013-11-22', 'N', null, 'tester@example.com', 'tester@example.com');

-- Populate Application
insert into SRM_OWNER.APPLICATION (APPLICATION_ID, NAME) values (1, 'Hot Checkout');
insert into SRM_OWNER.APPLICATION (APPLICATION_ID, NAME) values (2, 'Downtime');
insert into SRM_OWNER.APPLICATION (APPLICATION_ID, NAME) values (3, 'Problem Report');
insert into SRM_OWNER.APPLICATION (APPLICATION_ID, NAME) values (4, 'ePAS');

-- Populate Status
insert into SRM_OWNER.STATUS (STATUS_ID, NAME) values (0, 'Not Applicable');
insert into SRM_OWNER.STATUS (STATUS_ID, NAME) values (1, 'Ready');
insert into SRM_OWNER.STATUS (STATUS_ID, NAME) values (50, 'Checked');
insert into SRM_OWNER.STATUS (STATUS_ID, NAME) values (100, 'Not Ready');
insert into SRM_OWNER.STATUS (STATUS_ID, NAME) values (150, 'Masked (Director)');
insert into SRM_OWNER.STATUS (STATUS_ID, NAME) values (200, 'Masked (Crew Chief)');
insert into SRM_OWNER.STATUS (STATUS_ID, NAME) values (250, 'Masked (Administrator)');

-- Populate Region
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (1, 'Injector', '0I,1I,2I,3I,0L,1D,2D,3D,4D,5D,0R', 10);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (2, 'North Linac', '1L,3L,5L,7L,9L,BL,NL', 20);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (3, 'NE', '1S,3S,5S,7S,9S,BT', 30);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (4, 'ARC1', '1A', 40);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (5, 'SE', '1R,3R,5R,7R,9R', 50);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (6, 'South Linac', '2L,4L,6L,8L,AL,SL', 60);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (7, 'SW', '2S,4S,6S,8S,AS', 70);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (8, 'ARC2', '2A', 80);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (9, 'NW', '2R,4R,6R,8R,AR', 90);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (10, 'ARC3', '3A', 100);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (11, 'ARC4', '4A', 110);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (12, 'ARC5', '5A', 120);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (13, 'ARC6', '6A', 130);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (14, 'ARC7', '7A', 140);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (15, 'ARC8', '8A', 150);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (16, 'ARC9', '9A', 160);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (17, 'Extraction South', '2E,4E,6E,8E,AE', 170);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (18, 'Test Lab', 'TL Bldg. 58', 1000);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (19, 'Beam Switchyard / Transport', 'BSY,4C,4H,2T,4T,6T,8T,AT', 190);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (20, 'Hall A Line', '1P,1C', 200);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (21, 'Hall B Line', '2C', 210);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (22, 'Hall C Line', '3P,3C', 220);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (23, 'Hall A', '1H', 230);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (24, 'Hall B', '2M,2H', 240);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (25, 'Hall C', '3M,3H', 250);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (26, 'ARC10', 'AA', 260);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (27, 'Extraction North', 'BS,1E,3E,5E,7E,9E,BE', 270);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (28, 'Hall D Line', '5C,AD', 280);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (29, 'Hall D', '5H', 290);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (30, 'Site Wide', 'Other', 2000);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (31, 'LERF Vault', 'Bldg. 18', 1010);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (32, 'LERF Gallery', 'Bldg. 18', 1010);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (33, 'Experimental Equipment Lab', 'EEL Bldg. 90', 1000);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (34, 'Central Helium Liquefier', 'CHL Bldg. 8', 1000);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (35, 'LERF Gun Test Stand', 'GTS Bldg. 18', 1010);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (36, 'Cryogenics Test Facility', 'CTF Bldg. 57', 1000);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (37, 'Central Utility Plant', 'CUP Bldg. 60', 1000);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (38, 'South Extractor Service', 'W1 Bldg. 82', 1000);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (39, 'Hall A Beam Dump Cooling', 'Bldg. 91', 1000);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (40, 'Hall C Beam Dump Cooling', 'Bldg. 95', 1000);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (41, 'ABC Counting House', 'Bldg. 97', 1000);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (42, 'End Station Refrigeration', 'ESR Bldg. 102/104', 1000);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (43, 'Hall D Refrigeration', 'Bldg. 201', 1000);
insert into SRM_OWNER.REGION (REGION_ID, NAME, ALIAS, WEIGHT) values (44, 'UITF Vault', 'TL Bldg. 58', 1500);

-- Populate Categories
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (0, 'JLAB', null, 1);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (1, 'CEBAF', 0, 1);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (2, 'LERF', 0, 2);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (3, 'Other', 0, 50);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (4, 'Cryo', 0, 3);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (5, 'Facilities', 0, 4);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (6, 'Gun/Laser', 1, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (7, 'Magnets', 1, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (8, 'Operations', 1, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (9, 'Radiation Controls', 1, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (10, 'Vacuum', 1, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (11, 'Safety Systems', 1, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (14, 'Beam Dumps', 1, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (15, 'Info Systems', 1, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (17, 'Diagnostics', 1, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (18, 'RF', 1, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (26, 'Viewers', 17, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (27, 'BPMs', 17, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (30, 'Current Monitors', 17, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (31, 'Trim Supply', 7, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (32, 'Box Supply', 7, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (33, 'Beamline Vacuum', 10, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (34, 'SRF Vacuum', 10, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (35, 'Cold RF', 18, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (41, 'PSS', 11, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (42, 'MPS', 11, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (43, 'BELS', 11, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (161, 'Gun', 6, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (162, 'Laser', 6, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (205, 'Global Diagnostics', 17, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (241, 'CHL', 4, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (242, 'ENDSTATIONS', 4, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (262, 'UPS', 15, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (263, 'Servers', 15, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (264, 'Network', 15, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (281, 'Correctors', 31, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (283, 'HVAC', 5, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (284, 'LCW', 5, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (285, 'Control System', 1, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (301, 'Nature', 3, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (302, 'Unknown/Missing', 3, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (321, 'Software', 15, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (381, 'Beam Transport', 3, 1);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (401, 'Hall D', 0, 15);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (402, 'Hall C', 0, 14);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (403, 'Hall B', 0, 13);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (404, 'Hall A', 0, 12);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (405, 'Hall D Photon Beam', 401, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (406, 'Hall D Solenoid', 401, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (407, 'Hall D Detectors', 401, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (461, 'Hall B Beamline', 403, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (465, 'Hall Downtime', 3, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (466, 'Hall B Detectors', 403, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (467, 'Hall B HPS Detector', 466, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (481, 'LERF Beam Dumps', 2, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (482, 'LERF Beam Transport', 2, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (483, 'LERF Control System', 2, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (484, 'LERF Diagnostics', 2, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (485, 'LERF Info Systems', 2, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (486, 'LERF Magnets', 2, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (487, 'LERF Operations', 2, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (488, 'LERF RF Systems', 2, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (489, 'LERF Radiation Control', 2, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (490, 'LERF Safety Systems', 2, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (491, 'LERF Gun/Laser', 2, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (492, 'LERF Vacuum', 2, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (494, 'LERF Software', 485, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (495, 'LERF Box Supply', 486, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (496, 'LERF Trim Supply', 486, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (497, 'LERF Cold RF', 488, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (498, 'LERF Warm RF', 488, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (499, 'LERF MPS', 490, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (500, 'LERF PSS', 490, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (501, 'LERF Laser', 491, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (502, 'LERF Gun', 491, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (503, 'LERF Gun HV', 491, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (504, 'LERF SRF Vacuum', 492, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (505, 'LERF Warm Vacuum', 492, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (521, 'Hall B PRad Detector', 466, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (541, 'Hall B CLAS12 Detector', 466, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (545, 'CLAS12 TOF', 541, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (547, 'CLAS12 DC', 541, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (561, 'Hall B SuperConducting Magnets', 403, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (562, 'CLAS12 FT', 541, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (564, 'CLAS12 MVT', 541, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (582, 'Hall D Data Monitoring', 401, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (583, 'Hall C Magnets', 402, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (603, 'Hall A Magnets', 404, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (604, 'Noncredited Controls', 3, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (605, 'Level 1 Controls', 604, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (606, 'Level 2 Controls', 604, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (623, 'Sweep Procedures', 41, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (643, 'UITF', 0, 20);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (645, 'UITF Beam Dumps', 643, 100);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (646, 'UITF Beam Transport', 643, 100);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (647, 'UITF Control System', 643, 100);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (648, 'UITF Diagnostics', 643, 100);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (649, 'UITF Info Systems', 643, 100);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (650, 'UITF Magnets', 643, 100);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (651, 'UITF Operations', 643, 100);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (652, 'UITF RF Systems', 643, 100);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (653, 'UITF Radiation Control', 643, 100);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (654, 'UITF Safety Systems', 643, 100);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (655, 'UITF Source', 643, 100);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (656, 'UITF Vacuum', 643, 100);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (663, 'UITF Gun/Laser', 643, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (664, 'UITF Gun', 663, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (665, 'UITF Laser', 663, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (703, 'UITF Beamline Vacuum', 656, 1000);
insert into SRM_OWNER.CATEGORY (CATEGORY_ID, NAME, PARENT_ID, WEIGHT) values (743, 'HDR', 242, 1000);

CREATE SEQUENCE SRM_OWNER.CATEGORY_ID
    INCREMENT BY 1
    START WITH 744
    NOCYCLE
	NOCACHE
	ORDER;