package org.jlab.srm.persistence.enumeration;

/**
 * @author ryans
 */
public enum AllChangeType {
    UPGRADE,
    DOWNGRADE,
    CASCADE,
    COMMENT,
    ADD_COMPONENT,
    DELETE_COMPONENT,
    RENAME_COMPONENT,
    MASK,
    UNMASK,
    POWER,
    UNPOWER,
    LINK,
    UNLINK,
    MODIFY_REGION,
    COMPONENT_SUBSYSTEM,
    ADD_SUBSYSTEM,
    DELETE_SUBSYSTEM,
    RENAME_SUBSYSTEM,
    REORGANIZE_SUBSYSTEM,
    ADD_CATEGORY,
    DELETE_CATEGORY,
    RENAME_CATEGORY,
    REORGANIZE_CATEGORY
}
